[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle dynamic routes
[[redirects]]
  from = "/tours/:slug"
  to = "/tours/:slug/index.html"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug/index.html"
  status = 200

[[redirects]]
  from = "/news/:id"
  to = "/news/:id/index.html"
  status = 200

# Fallback for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"